SELECT DISTINCT CITY FROM STATION WHERE LOWER(SUBSTRING(CITY, -1)) IN ('a', 'e', 'i', 'o', 'u');

-- SELECT DISTINCT CITY FROM STATION WHERE LOWER(SUBSTRING(CITY, LENGTH(CITY), 1)) IN ('a', 'e', 'i', 'o', 'u');