SELECT DISTINCT CITY FROM STATION WHERE LOWER(SUBSTRING(CITY, 1, 1)) NOT IN ('a','e','i','o','u');

/*
SELECT DISTINCT city FROM STATION 
WHERE (CITY NOT LIKE 'a%'
        AND CITY NOT LIKE 'e%'
        AND CITY NOT LIKE 'i%' 
        AND CITY NOT LIKE 'o%'
        AND CITY NOT LIKE 'u%'
    );
*/