SELECT H.HACKER_ID, H.NAME 
FROM HACKERS H, SUBMISSIONS S, DIFFICULTY D , CHALLENGES C
WHERE S.HACKER_ID  = H.HACKER_ID 
      AND S.CHALLENGE_ID = C.CHALLENGE_ID 
      AND D.DIFFICULTY_LEVEL  = C.DIFFICULTY_LEVEL
      AND S.SCORE = D.SCORE
GROUP BY 
      H.HACKER_ID, H.NAME 
HAVING 
      COUNT(S.HACKER_ID) > 1
ORDER BY
      COUNT(S.HACKER_ID) DESC,
      S.HACKER_ID